version: '3.7'

services:
  nginx:
    container_name: nginx
    restart: unless-stopped
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/certificates/:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal_net

  sftp:
    image: atmoz/sftp
    volumes:
      - sftp_data:/home/foo/upload
    networks:
      - internal_net
    command: foo:pass:1001

  filebrowser:
    image: filebrowser/filebrowser
    volumes:
      - sftp_data:/srv
    environment:
      - FB_BASEURL=/
    networks:
      - internal_net

networks:
  internal_net:

volumes:
  sftp_data:
